Started work on Mealy machines
flapjs/vanilla pull request #37
Opened 2023-02-14 00:34 UTC by shishir03

2023-02-16 02:01 UTC, Lexseal commented
Thanks for doing that! I will take a look soon been busy lately...

2023-03-03 18:48 UTC, Lexseal requested changes
Overall excellent work @shishir03 and @benjxia! Just a couple of missing details. Very impressive for you guys to contribute so early after joining : )

2023-03-03 18:48 UTC, Lexseal commented on index.html
> +    <select id="select_machine">  <!-- value needs to match consts.MACHINE_TYPES -->
Nice thanks for the comment

2023-03-03 18:48 UTC, Lexseal commented on package.json
> +    "jest-environment-jsdom": "^29.4.3",
@benjxia Did we end up using that?

2023-03-03 18:48 UTC, Lexseal commented on scripts/compute.js
> +    let mealy_output = mealy_step(graph, cur_state, input.charAt(i));
You probably want to check the output here to see if it's undefined. If so, end the computation early. With the current code, I have run into issues reproducible by the following steps:
1. [Click this machine](https://flapjs--pr37-34-mealy-and-moore-m-xbs5ed4s.web.app/#Mealyq0:353:662:40:1;q1:531:974:40:0;q2:769:896:40:0;0:1:1%CE%B5%CE%B50R:5:0:5:-21~1:2:0%CE%B5%CE%B51R:5:0:18:18~)
2. Input 01 and hit step or run until invalid prompt shows
3. Input 10 and hit step or run. Expecting the machine to output 01 but says undefined.

2023-03-03 18:48 UTC, Lexseal commented on scripts/compute.js
> +    cur_state = moore_step(graph, cur_state, input.charAt(i));
Probably the same here

2023-03-03 18:48 UTC, Lexseal commented on scripts/graph_components.js
> +    return consts.DEFAULT_MOORE_TRANSITION;
This symbol is undefined. I think we should just remove this line

2023-03-03 18:48 UTC, Lexseal commented on scripts/graph_components.js
> +    mealy_output: mealy_output ? mealy_output : get_empty_symbol()
Since we are doing a default moore output, should we also do a default mealy output instead of using empty here? Can literally just be the same

2023-03-03 18:48 UTC, Lexseal commented on scripts/index.js
> +    if (v && !menus.is_Mealy()) {     // Mealy machines do not have a final accept state
This is trickly. If you want to enforce the UI consistency, i.e. mealy and moore cannot have double circles, then you would have to do it in more places. There are three I can think of:
1. Moore machine
2. Mealy machine context menu
3. Moore machine context menu

Otherwise, you might consider dropping this requirement and let users still create final states. They just won't be used during the computation and are purely ornamental

2023-03-03 18:48 UTC, Lexseal commented on scripts/permalink.js
> +                to_string_field(edge.mealy_output)            +
Can you also do the same for moore? Currently, it doesn't hash correctly I believe.

2023-03-06 20:59 UTC, shishir03 commented on scripts/compute.js
> +    let mealy_output = mealy_step(graph, cur_state, input.charAt(i));
![image](https://user-images.githubusercontent.com/31488575/223229205-c716cc21-66e0-40bb-a960-623dc159288d.png)
That's odd, I tried running the machine on the input 10 and it worked.

2023-03-06 23:12 UTC, benjxia commented on package.json
> +    "jest-environment-jsdom": "^29.4.3",
nope, removed it.

2023-03-06 23:22 UTC, benjxia commented on package.json
> +    "jest-environment-jsdom": "^29.4.3",
nvm it was being used i forgot lmao

2023-03-10 05:39 UTC, Lexseal commented
Just to clarity, the only thing we are waiting for is Moore permalink right? @benjxia

2023-03-10 05:54 UTC, Lexseal commented on scripts/permalink.js
> +                to_string_field(edge.mealy_output)            +
Huh wait edges do not have moore_output though...

2023-03-28 18:37 UTC, Lexseal commented
I checked the latest code by regenerating the test website [here](https://github.com/flapjs/vanilla/pull/37#issuecomment-1447223217). Everything seems to work except for the permalinks. Another nitpick is the default transition being epsilon instead of, say 0. Let's get these two small items fixed next quarter and get it merged!

2023-04-05 17:50 UTC, benjxia commented
NFA's are unable to run on input atm, they seem to still be able to step though

2023-04-05 18:36 UTC, benjxia commented
The tests still fail, just that now running an NFA on an input (in browser) will show whether it accepts or not.

2023-04-05 18:47 UTC, benjxia commented
Isolated the issue: Only deserialized NFA's are unable to run. I got class now so can't fix but that's seems to be the issue.

2023-04-12 17:40 UTC, Lexseal commented
I got you will fix the ci thing and review now

2023-04-12 17:55 UTC, Lexseal commented on scripts/permalink.js
> +    const output        = (type === 'Moore') ? parseFloat(fields[4]) : undefined;
Is this for backward compatibility?

2023-04-12 17:56 UTC, Lexseal commented on scripts/permalink.js
> +    const output        = (type === 'Moore') ? parseFloat(fields[4]) : undefined;
If not, consider adding the bit to every single serialization. It might be redundant but it's okay if we can streamline the code.

2023-04-19 06:15 UTC, shishir03 commented on scripts/permalink.js
> +    const output        = (type === 'Moore') ? parseFloat(fields[4]) : undefined;
I believe this was for backwards compatibility; in the serialize method the Moore output is handled as follows:

```result += to_string_field(Math.round(vertex.r)) + consts.FIELD_DELIM;
    result += to_string_field(vertex.moore_output)  + consts.FIELD_DELIM;
    const composite_bit = (vertex.is_start ? 1 : 0) + (vertex.is_final ? 2 : 0);
```

I was getting an error when running input for NFAs since they would not have an output field (and thus nothing would be added).

2023-04-19 06:27 UTC, shishir03 commented on scripts/permalink.js
> +    const output        = (type === 'Moore') ? parseFloat(fields[4]) : undefined;
Nvm, I was able to eliminate this issue (and apparently I didn't even need that check). Permalinks should hopefully be fully functional now.

2023-04-19 22:01 UTC, Lexseal commented
Hi, I added one more compatibility change. In particular, if the user has old localstore and decides to make a permalink, it would previously crash because we would call `to_string` on an undefined object. This is now fixed and I think it's all good to merge. Will let you guys do the honors

2023-04-19 22:02 UTC, Lexseal approved these changes

2023-04-19 22:05 UTC, merged