Beta build
flapjs/vanilla pull request #62
Opened 2024-11-28 01:05 UTC by MerujSargsyan

I have implemented the major features for the machines DFA, NFA and Turing, and I have placed some of the tests I have done inside a PDF within the test repository. Although I have found these bugs, they are a relatively minor or rare case, which although I do plan to correct, I think it is a good time to try it. If you would like me to completely fix all bugs before committing please let me know @Lexseal !

2024-12-02 02:52 UTC, Lexseal commented
Woah thank you so much for your fantastic work! It's so cool!

I am guessing you were referring to 1) state names overlapping the diagram and 2) self-loops labels overlapping each other?

Do you have any suggestions on how to fix these two issues? I think self-loops will be quite common so it's more of an issue. IIRC in our textbook they use the shorthand notation, combining the labels. Is that something you can implement?

2024-12-02 03:44 UTC, Lexseal commented
okay great! The two angles are where the mouse pointer leaves and re-enters the node. The angle is in rad and counter-clockwise. Suppose the mouse lefts the node at 3 o'clock, the angle will be 0. If the mouse re-enters at 12 o'clock, the angle will be pi/2.

2024-12-02 03:45 UTC, Lexseal commented
Will take a closer look tomorrow

2024-12-03 06:38 UTC, MerujSargsyan commented
I removed the no useless escape rule because it thought "\\begin" was using an unecessary escape. Am I clear to merge the branch?

2024-12-04 03:37 UTC, Lexseal requested changes
Thank you for your contribution. A couple of minor things in the inline comment and one major issue here

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/5a7314cf-0b00-4ac2-8222-012bc9c6e964">

Tried it out and seems like overleaf is angry about it... The circles did not show. Also perhaps include instruction in the alert to include the `tikz` package.

2024-12-04 03:37 UTC, Lexseal commented on .eslintrc.json
> +        "no-useless-escape": [
why is this needed again?

2024-12-04 03:37 UTC, Lexseal commented on scripts/consts.js
> +export const LATEX_ANGLE_SCALE = 8;
I know that there was not a blank line at the end before, but can you add one please?

2024-12-04 03:37 UTC, Lexseal commented on scripts/index.js
> +  // TODO
please remove // TODO if it's not needed anymore

2024-12-04 03:37 UTC, Lexseal commented on scripts/index.js
> +    navigator.clipboard.writeText(latex_str)
This is somehow not working for me and I get `undefined` copied to my clipboard. That said, the console does log the string.

2024-12-04 03:37 UTC, Lexseal commented on scripts/index.js
> +    navigator.clipboard.writeText(latex_str)
Oh see your comment below that clipboard is only available in secure context. This shouldn't be a problem on the actual website since we have https. But how come it doesn't work on localhost?

2024-12-04 03:37 UTC, Lexseal commented on scripts/latex.js
> +  console.log(output);
Maybe get rid of the console log and add a new line please?

2024-12-04 03:37 UTC, Lexseal commented on scripts/linalg.js
> +export function angle(v1, v2) {
The argument is a bit misleading. Maybe change `v1` and `v2` to `pt1` and `pt2`. The comment above is also a little strange. You seem to be computing the angle between the vector starting at `v1` and ending at `v2` with the x-axis right?

2024-12-04 03:40 UTC, Lexseal commented on .eslintrc.json
> +        "no-useless-escape": [
okay gotcha https://github.com/flapjs/vanilla/pull/62#issuecomment-2513681479

2024-12-04 03:41 UTC, Lexseal commented
also if you wanna generate a firebase preview you can comment out [this line](https://github.com/flapjs/vanilla/blob/3671d3f3030d120259b894e56c980a8ad52d5577/.github/workflows/firebase-hosting-pull-request.yml#L8) in your branch.

2024-12-04 03:55 UTC, MerujSargsyan commented on scripts/index.js
> +    navigator.clipboard.writeText(latex_str)
I believe it has to do with localhost not being a secure network or something, maybe it cannot force a clipboard change unless it is secure? Note that this problem also happens with the permalink feature in local host.

2024-12-04 03:57 UTC, MerujSargsyan commented on scripts/latex.js
> +  console.log(output);
would it be okay if I left it under some condition like:

if(debug) console.log(output);

because as mentioned before, the output does not copy into the clipboard so I had to copy and paste manually

2024-12-04 03:59 UTC, MerujSargsyan commented on scripts/linalg.js
> +export function angle(v1, v2) {
What i meant by x-axis is the relation of the angle, meaning that the x-axis was 0 degrees and continuing counterclockwise. How do you suggest I rephrase this?

2024-12-04 03:59 UTC, Lexseal commented on scripts/latex.js
> +  console.log(output);
yeah of course. what you can also do is to follow [this](https://github.com/flapjs/vanilla/pull/62#issuecomment-2516104446) and generate a temp website.

2024-12-04 04:03 UTC, Lexseal commented on scripts/linalg.js
> +export function angle(v1, v2) {
oh just renaming the variables and modifying the comment should be good

2024-12-04 04:28 UTC, MerujSargsyan commented on scripts/consts.js
> +export const LATEX_ANGLE_SCALE = 8;
Done!

2024-12-04 04:28 UTC, MerujSargsyan commented on scripts/index.js
> +  // TODO
Done!

2024-12-04 04:28 UTC, MerujSargsyan commented on scripts/linalg.js
> +export function angle(v1, v2) {
Done!

2024-12-04 04:30 UTC, MerujSargsyan commented
When it comes to the image, there is actually a library from tikz that needs to be included in order to use those edges. 

You need: \usetikzlibrary{arrows}.

How can we inform the user of this? Maybe an alert when they click the button or something?

2024-12-04 16:59 UTC, Lexseal approved these changes
Thanks!

2024-12-04 16:59 UTC, Lexseal commented on scripts/linalg.js
> + * computes angle between two points in degrees with 0deg = x-axis, increasing counterclockwise
I think the comment should say:
Compute the angle between the x-axis and the vector starting in `pt1` and ending in `pt2`.

2024-12-04 16:59 UTC, Lexseal commented on scripts/linalg.js
> + * @returns {float} angle between pt1, pt2
same here

2024-12-04 16:59 UTC, Lexseal commented on scripts/latex.js
>  }
maybe a new line here?

2024-12-06 20:03 UTC, MerujSargsyan commented
is it cool if I merge this then work on the self loop positioning @Lexseal ?

2024-12-06 20:07 UTC, Lexseal commented
yeah go ahead!

2024-12-06 21:45 UTC, merged